# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               ANR IMPROVED
tagline:             ''
description:         ''
url:                 https://improved-anr.github.io/
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate]

# About/contact
author:
  name:              IMPROVED
  url:               https://improved-anr.github.io/
  email:             improved_anr@ml.univ-poitiers.fr

# Custom vars
version:             1.0.0
